use_frameworks!

platform :ios, '10.0'

target 'YCPhotoBrowser_Example' do
  pod 'YCPhotoBrowser', :path => '../'
  pod 'SDWebImage'
  pod 'Kingfisher'
  target 'YCPhotoBrowser_Tests' do
    inherit! :search_paths

    
  end
end
